### ISSUE TITLE
publish package on PyPi

### ISSUE THREAD

**Issue by ilka-schulz** [Zahner-elektrik/Thales-Remote-Python#1]
I see that the driver for other Zahner devices [is already publish on PyPi](https://pypi.org/project/zahner-potentiostat/). Can this library please be published as well?

The README says:

> Download the subdirectory [thales_remote](https://github.com/Zahner-elektrik/Thales-Remote-Python/blob/main/thales_remote) and put this directory into your source directory where your Python script is located.

This might work for development but is absolutely not manageable for production use. I want to distribute my software using Zahner libraries to colleagues and onto various lab PCs in the future. I would prefer to just add the dependency to my `pyproject.toml` and let `pip` install the dependency, like with every other dependency.

**Comment by maxkrapp1** [comment]
Yes, we plan to do this in the near future. When we release the next revision.

**Comment by ilka-schulz** [comment]
I forgot to tag this issue in the PR, which is #3.

**Comment by maxkrapp1** [comment]
Published with release [v1.0.0](https://github.com/Zahner-elektrik/Thales-Remote-Python/releases/tag/v1.0.0)

https://pypi.org/project/thales-remote/
