### ISSUE TITLE
documentation: how to continuously read data?

### ISSUE THREAD

**Issue by ilka-schulz** [Zahner-elektrik/Thales-Remote-Python#14]
I found the `set<technique_name>Output<Path|File>` methods but I struggle to load the measured data into my application:

1. How do I save data when using constant current / constant voltage technique?
2. It appears that the data are written to the host machine's file system for CV, IE, EIS and Sequence techiques. I really need the data on the client machine – the user sits at the client machine and all program logic is implemented in the client.
3. Any chance to directly get the data into Python? I found some methods to read Thales data files from disk but this would not work due to item 2 on this list and I would really need to know the *exact* output file name which this library does not provide.

I really want to load the data into my application and not have the user manually click around. The `zahner_potentiostat` library for PP2x2 devices supports this feature seamlessly; can I have the same for Zennium devices?

**Comment by maxkrapp1** [comment]
Take a look at the two examples. The file exchange is described here.

https://github.com/Zahner-elektrik/Thales-Remote-Python/blob/main/Examples/FileExchangeEIS/FileExchangeEIS.ipynb
https://github.com/Zahner-elektrik/Thales-Remote-Python/blob/main/Examples/HeartBeatLiveData/HeartBeatLiveData.ipynb

If you simply switch on the potentiostat and are not in any measurement method, data is not saved anywhere.

For the measurement data in constant voltage and constant current techniques, it is best to use the sequencer. With the sequencer you have to get the file manually after the measurement with [aquireFile](https://doc.zahner.de/thales_remote/file_interface.html#thales_remote.file_interface.ThalesFileInterface.aquireFile).

Yes, it can only be written to the host file system. The problem can be solved by setting the file name to Individual, then the files will have exactly the name you specified.

The concept as in the `zahner_potentiostat` library is impossible to realize with Thales & Term.

**Comment by ilka-schulz** [comment]
@maxkrapp1 Thanks a lot! I will try out the sequencer but I think it is way, way too complicated for some simple constant current / constant voltage applications. The majority of users does probably not want to work through the sequencer manual and learn some Zahner language. It looks doable but it demands immense frustration tolerance from the user. Developing a sequence file, transmitting it to the host, setting the output file path, running the sequence, receiving some output file back, reading the file from disk and deleting the files from the host and/or client machine is just way too many steps.

Maybe add a wrapper method which does all the required steps concerning file transfer, etc.? I think this is exactly the purpose of an ergonomic library to hide all these steps behind an abstraction.

**Comment by maxkrapp1** [comment]
Other customers solve this by simply measuring voltage and current cyclically as in the following snippet from the [Basic Introduction](https://github.com/Zahner-elektrik/Thales-Remote-Python/blob/main/Examples/BasicIntroduction/BasicIntroduction.ipynb). This would probably also be the easiest solution for you, then you can also freely define the format in which you save the data.

```python
    for i in range(5):
        print(f"Potential:\t{zahnerZennium.getPotential():>10.6f} V")
        print(f"Current:\t{zahnerZennium.getCurrent():>10.3e} A")
```
And then something like [numpy.savetxt](https://numpy.org/doc/stable/reference/generated/numpy.savetxt.html#numpy-savetxt)

For this simple application, I agree with you that the sequencer is too complex. We have already considered your suggestion in a similar way, but the implementation is not possible.
