### ISSUE TITLE
file_interface.aquireFile is misspelled

### ISSUE THREAD

**Issue by ilka-schulz** [Zahner-elektrik/Thales-Remote-Python#15]
acquire is spelled with additional `c`. But maybe keep the old method names in addition to the corrected type and throw deprecation warnings?

**Comment by maxkrapp1** [comment]
Thanks for the tip.
This is somehow misspelled by despite the Spell Checker.

**Comment by maxkrapp1** [comment]
There was also a critical bug in the function and it stopped working.
