### ISSUE TITLE
documentation / feature: allow no current limit on CV measurement

### ISSUE THREAD

**Issue by ilka-schulz** [Zahner-elektrik/Thales-Remote-Python#16]
The documentation does say how to disable current limits on CV measurements:

https://doc.zahner.de/thales_remote/script_wrapper.html#thales_remote.script_wrapper.ThalesRemoteScriptWrapper.setCVMaximumCurrent

How could I disable current limits and could you please add the info to the documentation?

**Comment by maxkrapp1** [comment]
Unfortunately, this is not clear from the documentation - there is always a maximum current and a minimum current in the CV which must be set.
According to these values, the meter selects the current measurement range.

**Comment by ilka-schulz** [comment]
@maxkrapp1 Thanks for the info! Are you saying that if I select a too large maximum current, the measurement will be less precise? If so, is this a limitation by hardware or a limitation by software? Is there a chance that this limitation can be lifted in the future?

**Comment by maxkrapp1** [comment]
Yes, if you set the current too high, the signal will be too small and noisy.
 
The shunt is determined so that the maximum value of the amount of min or max fits into the measuring range of the shunt.

This can not be changed.
