### ISSUE TITLE
documentation: please make ThalesRemoteError have human-readable error messages

### ISSUE THREAD

**Issue by ilka-schulz** [Zahner-elektrik/Thales-Remote-Python#18]
The class `ThalesRemoteError` currently just shows an error code but no human-readable error message. Could please add that information?

Also see #17

**Comment by maxkrapp1** [comment]
The table with the error numbers must be taken from the Remote manual. A complete documentation is not planned, because the errors have partly cryptic descriptions.

https://doc.zahner.de/manuals/remote2.pdf
