### ISSUE TITLE
no comma (,) characters allowed in file name, incomprehensible error message, unintuitive crash time point

### ISSUE THREAD

**Issue by ilka-schulz** [Zahner-elektrik/Thales-Remote-Python#23]
I used a file name with a comma (`,`) character in it for my EIS measurements (`ThalesRemoteScriptWrapper.setEISOutputFileName`). This made the Thales software crash after an EIS measurement was successfully done with the error message `Manual program interrupt!`. Both the point in time of the crash as well as the error message did not really hint me into the right direction, maybe at least that can be approved?

**Comment by maxkrapp1** [comment]
Unfortunately, file path handling in Thales is a complicated matter that can no longer be changed. As well as error handling and output in this case.

That's why we documented it in detail in the documentation of the method:
https://doc.zahner.de/thales_remote/script_wrapper.html#thales_remote.script_wrapper.ThalesRemoteScriptWrapper.setEISOutputFileName

"The basic name of the file, which is extended by a sequential number or the date and time. Only numbers, underscores and letters from a-Z may be used."

And in addition, you can read which characters are allowed in our Remote2 manual in Chapter 2.4.
https://doc.zahner.de/manuals/remote2.pdf

**Comment by ilka-schulz** [comment]
@maxkrapp1 Thank you for the quick response! I somehow overlooked the doccomment and just read the code of the function and the `setValue` function which it calls instead. I should really pay more attention to the comments :see_no_evil: 

Maybe the function should check for invalid input? Something like the following could help reduce debugging:
```python
def setEISOutputFileName(self, name: str) -> str:
    """ [...] """
    if re.compile("[^0-9a-zA-Z_]").search(name) is not None:
        raise ValueError("invalid file name: only roman letters, numbers and underscores allowed!")
    return self.setValue("EIS_ROOT", name)
```

However, I realized that dashes (`-`) and dots (`.`) are allowed, too, so maybe change the docstring and change the regex to `[^0-9a-zA-Z_\.-]`.

**Comment by maxkrapp1** [comment]
yes, that would be a possibility, but it has to be implemented more generally and everywhere where file names or paths are set remotely.

I will take this into account in the next release.

**Comment by maxkrapp1** [comment]
The next release will include this function, which will be called internally.

```python
  def _checkForForbiddenCharacters(self, string:str):
      if re.compile("[^0-9a-zA-Z_-]").search(name) is not None:
          raise ValueError("invalid file name: only roman letters, numbers and underscores allowed!")
      return
```

**Comment by maxkrapp1** [comment]
I have added these two functions which ensure that the paths and file names are correct. in addition, the path is checked to ensure that it is only on drives a-k.

```python
    def _checkForForbiddenCharactersInPath(self, string:str):
        """
        This function ensures that only the permitted characters appear in the path to:
        https://doc.zahner.de/manuals/remote2.pdf

        :param string: string to check.
        """
        pattern = re.compile(r"(^[a-k]{1}[:]{1}[\/\\0-9a-zA-Z_\+-]+$)")
        match = pattern.fullmatch(string)
        if match is None:
            raise ValueError(f"invalid path: \"{string}\"")
        return

    def _checkForForbiddenCharactersInFilename(self, string:str):
        """
        This function ensures that only the permitted characters appear in the filename to:
        https://doc.zahner.de/manuals/remote2.pdf

        :param string: string to check.
        """
        pattern = re.compile(r"(^[0-9a-zA-Z_\+-]+$)")
        match = pattern.fullmatch(string)
        if match is None:
            raise ValueError(f"invalid filename: \"{string}\"")
        return
```
