### ISSUE TITLE
ThalesRemoteScriptWrapper.setScanStrategy and others should expect an enum parameter

### ISSUE THREAD

**Issue by ilka-schulz** [Zahner-elektrik/Thales-Remote-Python#5]
This applies to:
- setScanStrategy
- setScanDirection
- setEISNaming
- setCVNaming

This issue is blocked by #4.

**Comment by maxkrapp1** [comment]
Yes that is a useful change. But I would keep the backwards compatibility.

**Comment by ilka-schulz** [comment]
Sure, you can easily keep it backward-compatible by declaring the type `Union[int, MyEnumType]` and then do an `isinstance` check in the method body.

**Comment by maxkrapp1** [comment]
I will add this in the next release.

**Comment by maxkrapp1** [comment]
This was fixed in release [v1.0.0](https://github.com/Zahner-elektrik/Thales-Remote-Python/releases/tag/v1.0.0)
