### ISSUE TITLE
use enum for message_type parameter in ThalesRemoteConnection class

### ISSUE THREAD

**Issue by ilka-schulz** [Zahner-elektrik/Thales-Remote-Python#8]

**Comment by maxkrapp1** [comment]
The message_type which must be used for the communication are unfortunately relatively freely and meaninglessly assigned numbers, so I think an enum is not necessary here.

**Comment by ilka-schulz** [comment]
I see... Maybe add some documentation on the matter? The parameter value documentation was leaving me with questions about which values are allowed and which values make sense.

**Comment by maxkrapp1** [comment]
This part of code can unfortunately only be maintained by Zahner employees with further knowledge about the communication with the Term software.
The whole connection.py should only be handled with great care. Since for example unfortunately also the sleeps are necessary.
