### ISSUE TITLE
ThalesRemoteConnection.connectToTerm() should raise an exception

### ISSUE THREAD

**Issue by ilka-schulz** [Zahner-elektrik/Thales-Remote-Python#9]
This method currently returns a `bool` which is C-style error propagation. This is prone to bugs because the errors can accidentally be ignored. Exceptions are still quite an old error propagation technique and it can be hard to determine where to catch them best (Java follows a good approach where you must declare your exception types) but I guess Python is an old language.

Or rewrite it in Rust. Rust's error handling is absolutely sleek. :crab: :wink:

**Comment by maxkrapp1** [comment]
Yes, since everywhere is worked with exception it makes at this point actually also more sense.

**Comment by maxkrapp1** [comment]
A `TermConnectionError` will be thrown in the new release.

**Comment by maxkrapp1** [comment]
This was fixed in release [v1.0.0](https://github.com/Zahner-elektrik/Thales-Remote-Python/releases/tag/v1.0.0)
